version: 0.7.6.{build}
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  project: WixEdit.sln
  verbosity: minimal
after_build:
- cmd: >-
    .\tools\wix-3.5.1322.0\candle.exe -ext WixNetfxExtension ".\installer\WixEdit.wxs" -dConfiguration=%CONFIGURATION% -dVERSION=%APPVEYOR_BUILD_VERSION%

    .\tools\wix-3.5.1322.0\light.exe -b .\installer -ext WixNetfxExtension -out WixEdit-%APPVEYOR_BUILD_VERSION%.msi WixEdit.wixobj


    7z a WixEdit-%APPVEYOR_BUILD_VERSION%-bin.zip .\bin\%CONFIGURATION% -xr!*.xml -xr!*.vshost*

    7z rn WixEdit-%APPVEYOR_BUILD_VERSION%-bin.zip %CONFIGURATION% bin

    7z a WixEdit-%APPVEYOR_BUILD_VERSION%-bin.zip .\templates .\wizard .\sample
artifacts:
- path: WixEdit-%APPVEYOR_BUILD_VERSION%.msi
- path: WixEdit-%APPVEYOR_BUILD_VERSION%-bin.zip